# Generated by Django 2.2.2 on 2019-06-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_page', '0002_auto_20190611_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(upload_to='img/Home-articles', verbose_name='Imagen'),
        ),
    ]
