# Generated by Django 2.2.2 on 2019-06-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_page', '0003_auto_20190612_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('objetive', models.TextField(max_length=1500)),
                ('review', models.TextField(max_length=1500)),
                ('studyPlan', models.FileField(upload_to='documents/Careers-docs', verbose_name='Study Plan')),
            ],
        ),
        migrations.AlterField(
            model_name='home',
            name='typeClass',
            field=models.CharField(choices=[('txtsimple', 'Texto Simple'), ('txtsimple-img', 'Texto con imagen'), ('txtimg-left', 'Texto con imagen a la izquierda'), ('txtimg-right', 'Texto con imagen a la derecha')], default='txtsimple', max_length=40),
        ),
    ]
