# Generated by Django 2.2.2 on 2019-06-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_page', '0004_auto_20190612_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreras',
            name='typeClass',
            field=models.CharField(choices=[('txtsimple', 'Texto Simple'), ('txtsimple-img', 'Texto con imagen'), ('txtimg-left', 'Texto con imagen a la izquierda'), ('txtimg-right', 'Texto con imagen a la derecha')], default='txtsimple', max_length=40),
        ),
    ]
