# Generated by Django 2.2.2 on 2019-06-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_page', '0005_carreras_typeclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursosDestacados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('resource', models.FileField(upload_to='Resource-Relevant', verbose_name='Recurso')),
                ('typeClass', models.CharField(choices=[('align-left', 'Bloque Izquierdo'), ('align-right', 'Bloque Derecho')], default='align-left', max_length=30)),
            ],
        ),
    ]
