# Generated by Django 2.2.2 on 2019-07-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_page', '0008_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='unityOne',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='unityThree',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='unityTwo',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
